export { default as ABiz } from './ABiz'
export { default as Astronaut } from './Astronaut'
export { default as CoffeeMug } from './CoffeeMug'
export { default as Dino } from './Dino'
export { default as ET } from './ET'
export { default as HolwsCastle } from './HolwsCastle'
export { default as Ocean } from './Ocean'
export { default as Octopus } from './Octopus'
export { default as Pepe } from './Pepe'
export { default as Potion } from './Potion'
export { default as Shapes } from './Shapes'
export { default as Shrimp } from './Shrimp'
export { default as Zen } from './Zen'
export * from './SuperMario'
